### ISSUE TITLE
求教carla-ppo

### ISSUE THREAD

**Issue by lovesuiyue** [HFY123/learngit#1]
你好，我能问几个关于carla-ppo的问题吗？
正如你在那个作者下面提的问题一样，我在训练的时候也是很多训练也是停滞的，等待一会又开始下一轮，请问你解决了吗？
另外训练出数据后，python run_eval.py --model_name name_of_your_model -start_carla 无法跑起来看效果，不知道为什么终端开始之后显示不了几秒就崩了？
因为刚入门的小白，无人能交流，寄希望于github了！！

**Comment by HFY123** [comment]
停滞问题我没有找到从本质上解决的方法，折中的办法是把他代码里判断在原定停留时间的阈值改小一点，这样停滞的时间能短一点。
我是用windows系统跑的，所以没有用-start_carla这个arg，都是先打开Carla然后运行代码跑模型。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HFY123/learngit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月4日(星期六) 晚上6:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[HFY123/learngit] 求教carla-ppo (Issue #1)





 
你好，我能问几个关于carla-ppo的问题吗？
 正如你在那个作者下面提的问题一样，我在训练的时候也是很多训练也是停滞的，等待一会又开始下一轮，请问你解决了吗？
 另外训练出数据后，python run_eval.py --model_name name_of_your_model -start_carla 无法跑起来看效果，不知道为什么终端开始之后显示不了几秒就崩了？
 因为刚入门的小白，无人能交流，寄希望于github了！！
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lovesuiyue** [comment]
那关于训练时,checkpoint模型保存有问题,我训练了近16K,模型只保存了几个,
而且还是最开始的几个,以至于后来训练的模型没有一个保存
我知道代码里讲的模型是择优保存,  我看训练过程的时候,看到的训练其实很好,为什么模型却不保存
请问你有遇到这样的问题吗? 希望能得到解答,谢谢!!!

**Comment by HFY123** [comment]
我针对自己的任务需求对奖励函数进行了重新设计，并且我训练的时候取消了随机出生点的设置，固定重复训练一条轨迹。
只有最开始的几个确实代表后面没有累计奖励更高的了，这个看不一定看得出来，我当时也发现了这个问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HFY123/learngit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 中午11:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HFY123/learngit] 求教carla-ppo (Issue #1)





 
那关于训练时,checkpoint模型保存有问题,我训练了近16K,模型只保存了几个,
 而且还是最开始的几个,以至于后来训练的模型没有一个保存
 我知道代码里讲的模型是择优保存,  我看训练过程的时候,看到的训练其实很好,为什么模型却不保存
 请问你有遇到这样的问题吗? 希望能得到解答,谢谢!!!
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lovesuiyue** [comment]
那这个情况与作者的描述差很多, 是什么原因导致的呢?  是不是没必要继续训练更多了啊,还是死等,训练很久很久......(之前训练了两天,那时候没看模型的情况,最后才发现模型根本就没有随训练而保存)
说回来,即使考虑到强化学习不容易收敛,考虑择优保存.那去改原作者的代码,有没有实用性和改的必要

**Comment by lovesuiyue** [comment]
那大神,提个无礼的请求,能看看你改的东西吗?

**Comment by HFY123** [comment]
我觉得没必要死等，他args里可以设置训练轮数的上限，不是太长的轨迹五百轮以下就行




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HFY123/learngit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 中午11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HFY123/learngit] 求教carla-ppo (Issue #1)





 
那这个情况与作者的描述差很多, 是什么原因导致的呢?  是不是没必要继续训练更多了啊,还是死等,训练很久很久......(之前训练了两天,那时候没看模型的情况,最后才发现模型根本就没有随训练而保存)
 说回来,即使考虑到强化学习不容易收敛,考虑择优保存.那去改原作者的代码,有没有实用性和改的必要
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lovesuiyue** [comment]
我明白了

**Comment by HFY123** [comment]
哈哈是之前硕士论文搞的，现在电脑上已经没有了，抱歉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HFY123/learngit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 中午11:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [HFY123/learngit] 求教carla-ppo (Issue #1)





 
那大神,提个无礼的请求,能看看你改的东西吗?
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lovesuiyue** [comment]
你能解答我的疑问都很好了,现在的人啊!卷的很,问个问题都没时间回!!!
感谢!   感谢!!!
